fee/urls.py
from django.urls import path
from .views import (
        GenerateChallan,
        UnpaidChallan,
        generated_challan,
        payChallan,
        fee_defaulter,
        fee_main,
        fee_received
    )


app_name = 'fee'
urlpatterns = [
    path('', fee_main, name="fee_main"),
    path('generatechallan', GenerateChallan, name='generate_challan'),
    path('generatedChallan', generated_challan, name='generated_challan'),
    path('unpaidChallan/', UnpaidChallan, name='unpaid_challan'),
    path('payChallan', payChallan, name='pay_challan'),
    path('FR/<str:date>/fee_received', fee_received, name='fee_received'),  
    path('feedefaulter', fee_defaulter, name='fee_defaulter'),
]

intelexcel_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

app_name = 'main'

urlpatterns = [
    path('backend/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('fee/', include('fee.urls')),
    path('academic/', include('academic.urls')),
    path('account/', include('account.urls')),
    path('messages/', include('message.urls')),
    path('payroll/', include('payroll.urls')),
    path('', include('frontend_home.urls')),
    path('student_dashboard/', include('student_dashboard.urls')),
    path('website_setting/', include('websitesetting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py

from django.urls import path
from academic.views import SectionCreate, SectionUpdate,  SectionDelete
from .views import (
    StudentView,
    AttendanceMark,
    AttendanceSearch,
    AttendanceView,
    IndividualMarksView,
    AdmissionCreate, 
    AdmissionView, 
    AdmissionDelete, 
    AdmissionUpdate, 
    AdmissionDetail,
    StudentMarkSearch,
    StudentMarkCreate,
    MarkDistributionCreate,
    MarkDistributionUpdate,
    MarkDistributionDelete,
    ExamsView,
    ExamsDetail,
    ExamsCreate,
    ExamsUpdate,
    ExamsDelete,
    get_class_asignments,
    SendEmail_SaveData,
    SendEmailForExam,
    get_fee,
    get_subject_by_class,
    get_already_marks,
    getting_marks_from_calculated
    )


app_name = 'student'
urlpatterns = [
    path('', StudentView, name='student_view'),
    path('admission/create/', AdmissionCreate.as_view(), name='admission_create'),
    path('admission/view/', AdmissionView.as_view(), name='admission_view'),
    path('admission/view/<int:pk>/detail', AdmissionDetail.as_view(), name='admission_detail'),
    path('admission/view/<int:pk>/update', AdmissionUpdate.as_view(), name='admission_update'),
    path('admission/view/<int:pk>/delete', AdmissionDelete.as_view(), name='admission_delete'),
    path('createSection/', SectionCreate.as_view(), name='create_section'),
    path('updateSection/<int:pk>', SectionUpdate.as_view(), name='update_section'),
    path('deleteSection/<int:pk>/delete', SectionDelete.as_view(), name='delete_section'),
    path('viewexams/view', ExamsView.as_view(), name='view_exams'),
    path('createexams/', ExamsCreate.as_view(), name='create_exams'),
    path('detailexams/<int:pk>/detail', ExamsDetail.as_view(), name='detail_exams'),
    path('updateexams/<int:pk>/edit', ExamsUpdate.as_view(), name='update_exams'),
    path('deleteexams/<int:pk>/delete', ExamsDelete.as_view(), name='delete_exams'),
    path('SendEmail_SaveData/', SendEmail_SaveData, name='SendEmail_SaveData'),
    path('sendemailforexam/', SendEmailForExam.as_view(), name='sendemailforexam'),
    path('attendance/view', AttendanceView.as_view(), name='attendance_view'),
    path('attendance/search', AttendanceSearch.as_view(), name='attendance_search'),
    path('attendance/mark', AttendanceMark.as_view(), name='attendance_mark'),
    path('student_mark/search', StudentMarkSearch.as_view(), name='student_mark'),
    path('student_mark/add', StudentMarkCreate.as_view(), name='student_mark_add'),
    path('mark_distribution/create', MarkDistributionCreate.as_view(), name='mark_distribution_create'),
    path('mark_distribution/<int:pk>/update', MarkDistributionUpdate.as_view(), name='mark_distribution_update'),
    path('mark_distribution/<int:pk>/delete', MarkDistributionDelete.as_view(), name='mark_distribution_delete'),
    path('report/<int:student_name>/info', IndividualMarksView.as_view(), name='view_individual_marks'),    
    path('report/<int:student_name>/info?year&tab', IndividualMarksView.as_view(), name='view_individual_marks2'),    
    path('get_fee', get_fee, name="get_fee"),
    path('get_subject_by_class/', get_subject_by_class , name="get_subject_by_class"),
    path('get_already_marks/', get_already_marks , name="get_already_marks"),
    path('get_class_asignments/<int:pk>/class/<int:class_name>/subject/<int:subject>', get_class_asignments , name="get_class_asignments"),
    path('getting_marks_from_calculated/', getting_marks_from_calculated , name="getting_marks_from_calculated")
]

student/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from academic.models import Classes, Section, Subject
from django.db.models import Q
from django.contrib.postgres.fields import ArrayField

# from django.http import HttpRequest

# print(request.session['school_user_id'],'======================sada=as=ad=asd=dasd=sd=sd=d=d=ssd=asd=')

options = [
    ('1', 'Present'),
    ('2', 'Absent'),
    ('3', 'Leave'),
    ('4', 'Late-In'),
    ('4', 'Off By School'),
]

month_name = [
    ('1', 'Jan'),
    ('2', 'Feb'),
    ('3', 'Mar'),
    ('4', 'Apr'),
    ('5', 'May'),
    ('6', 'Jun'),
    ('7', 'Jul'),
    ('8', 'Aug'),
    ('9', 'Sep'),
    ('10', 'Act'),
    ('11', 'Nov'),
    ('12', 'Dec')
]

types = [
    ('exam', 'Exam'),
    ('attendance', 'Attendance'),
    ('class test', 'Class Test'),
    ('assignment', 'Assignment'),
   
]
exam_type = [
    ('midterm', 'midterm'),
    ('final', 'final'),
    ('classtest', 'class test'),
    ('assignment', 'assignment')

]
# Create your models here.
gender = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
yes_no = [('0', 'NO'), ('1', 'YES')]

def get_default_something():
    return {'id': ['no'], 'reject_list': []}

class Admission(models.Model):
    admission_date = models.DateField()
    admission_class = models.ForeignKey(Classes, on_delete=models.CASCADE)
    admission_section = models.ForeignKey(Section, on_delete=models.CASCADE)
    admission_registration = models.CharField(max_length=35)
    name_of_student = models.CharField(max_length=35)
    father_name = models.CharField(max_length=35)
    father_cnic = models.CharField(max_length=35)
    cast = models.CharField(max_length=35, default='no')
    father_profession = models.CharField(max_length=35)
    date_of_birth = models.DateField()
    contact = models.CharField(max_length=35)
    address = models.TextField()
    gender = models.CharField(max_length=10, default='Male', choices=gender)
    recieve_admissin_fee_with_admission = models.CharField(default='no',max_length=15, choices=yes_no)
    monthly_tution_fee = models.IntegerField(default=0)
    concession_fee = models.IntegerField(default=0)
    annual_fund = models.IntegerField(default=0)
    free_student = models.CharField(default='no',max_length=3, choices=yes_no)
    father_email_address = models.EmailField(max_length=100 ,blank=True)
    Student_email_address = models.EmailField(max_length=100 ,blank=True)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    photo = models.ImageField(upload_to='students', default='noimage.png')
    status = models.IntegerField(default=1)
    password = models.CharField(max_length=255, default="student123")
    status_date = models.DateField(default=timezone.now().strftime('%Y-%m-%d'))
    
    class Meta:
        ordering = ['-id']
        db_table = 'admission'

    def __str__(self):
        return self.name_of_student

    def get_absolute_url(self):
        return reverse_lazy('student:admission_view')


# class TutionFee(models.Model):
#     student_id = models.ForeignKey(Admission, on_delete=models.CASCADE)
#     tution_fee_month = models.CharField(max_length=10, choices=month_name)
#     tution_fee = models.IntegerField()
#     admission_fee = models.IntegerField()
#     scient_fee = models.IntegerField()
#     game_fee = models.IntegerField()
#     fee_card = models.IntegerField()
#     library_fee = models.IntegerField()
#     identity_card = models.IntegerField()
#     registration_fee = models.IntegerField()
#     late_admission_fee = models.IntegerField()
#     computer_fee = models.IntegerField()
#     prospectus_fee = models.IntegerField()
#     security_fee = models.IntegerField()
#     receive_annual_fund_with_admission = models.CharField(max_length=15, choices=[
#         ('no', 'NO'), ('yes', 'YES')])
#     paid_annual_fund = models.IntegerField()  # display after select
#     total_amount_received = models.IntegerField()
#     send_sms = models.CharField(max_length=15, choices=[
#         ('no', 'NO'), ('yes', 'YES')])
#     sms_message = models.TextField()
#     module_holder = models.CharField(max_length=50)
#     inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))


class Attendance(models.Model):
    student_id = models.ForeignKey(Admission, on_delete=models.CASCADE)
    registration = models.CharField(max_length=35)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    classes = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subjects = models.CharField(max_length=50)
    date = models.DateField()
    attendance_selection = models.CharField(max_length=20, choices=options, default='Present')
    remarks = models.TextField(default='No', null=True)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    current_month = models.CharField(max_length=20, default=str(timezone.now().strftime('%m/%Y')))

    class Meta:
        ordering = ['-id']
        db_table = 'attendance'
        
    def get_absolute_url(self):
        return reverse_lazy('student:attendance_mark')

    def __str__(self):
        return str(self.student_id)

    

class StudentMark(models.Model):
    student_name = models.ForeignKey(Admission, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    class_name = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    exam = models.FloatField()
    attendance = models.FloatField()
    class_test = models.FloatField()
    assignment = models.FloatField() 
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    current_month = models.CharField(max_length=20, default=str(timezone.now().strftime('%Y-%m')))
    class Meta:    
        ordering = ['-id']
        db_table = 'studentmark'

    def get_absolute_url(self):
        return reverse_lazy('student:student_mark')   



class MarkDistribution(models.Model):
    class_name = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subject_name = models.ForeignKey(Subject, on_delete=models.CASCADE)
    exam = models.IntegerField()
    attendance = models.IntegerField()
    class_test = models.IntegerField()
    assignment = models.IntegerField()
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        db_table = 'markdistribution'

    def get_absolute_url(self):
        return reverse_lazy('student:mark_distribution_create')

class Exams(models.Model):
    exams_name = models.CharField(max_length=100, unique=True)
    class_name = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subject_name = models.ForeignKey(Subject, on_delete=models.CASCADE)
    exam_type = models.CharField(max_length=20, choices=exam_type)
    marks = models.IntegerField()
    exam_detail_file = models.FileField('Exam Or Assignment Detail File',upload_to='exams', default='nofile.pdf', blank=True)
    open_date = models.DateField()
    due_date = models.DateField()
    remarks = models.TextField(blank=True)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    current_month = models.CharField(max_length=20, default=str(timezone.now().strftime('%Y-%m')))

    def __str__(self):
        return self.exams_name

    class Meta:
        ordering = ['-id']
        db_table = 'exams'

    def get_absolute_url(self):
        return reverse_lazy('student:view_exams')

class ExamEmail(models.Model):
    exam = models.ForeignKey(Exams, on_delete=models.CASCADE)
    student = ArrayField(models.CharField(max_length=200), blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    # mark_assigned = models.IntegerField(default=0)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    current_month = models.CharField(max_length=20, default=str(timezone.now().strftime('%Y-%m')))

    class Meta:
        ordering = ['-id']
        db_table = 'examemail'  

    def get_absolute_url(self):
        return reverse_lazy('student:create_exams')

class CalculateResults(models.Model):
    student = models.ForeignKey(Admission, on_delete=models.CASCADE)
    class_name = models.ForeignKey(Classes, on_delete=models.CASCADE)
    exam = models.ForeignKey(ExamEmail, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    marks = models.CharField(default='undeclared', max_length=20)
    total_marks = models.IntegerField(default=0)
    exam_type = models.CharField(max_length=50)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    current_month = models.CharField(max_length=20, default=str(timezone.now().strftime('%Y-%m')))
    
    class Meta:
        ordering = ['-id']
        db_table = 'calculateresults'  

    def get_absolute_url(self):
        return reverse_lazy('student:create_exams')


class StudentsMarks(models.Model):
    exam =  models.ForeignKey(Exams, on_delete=models.CASCADE)
    student =  models.ForeignKey(Admission, on_delete=models.CASCADE)
    marks = models.IntegerField()
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

templates/student/admission_view.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block innerlinks %}
{% include 'student/student_nav.html' %}
{% endblock %}
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">All Registerd Student List</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                               <a href="{% url 'student:admission_create' %}" class="btn btn-primary">New Admission</a>
                                <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th>S-No</th>
                                              <th>Photo</th>
                                              <th>Class</th>
                                              <th>Section</th>
                                              <th>Registration</th>
                                              <th>Name</th>
                                              <th>Father Name</th>
                                              <th>Contact</th>
                                              <th>Tution Fee</th>
                                              <th>Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       
                                       {% for admission in admission_view %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td><img src="{{ admission.photo.url }}" alt="" style="width:46px; height: 45px;"></td>
                                                <td>{{ admission.admission_class }}</td>
                                                <td>{{ admission.admission_section }}</td>
                                                <td>{{ admission.admission_registration }}</td>
                                                <td>{{ admission.name_of_student }}</td>
                                                <td>{{ admission.father_name }}</td>
                                                <td>{{ admission.contact }}</td>
                                                <td>{{ admission.monthly_tution_fee }}</td>
                                                <td>
                                                    <a href="{% url 'student:admission_update' pk=admission.pk %}" class="btn btn-labeled btn-success mb-2 mr-1">
                                                        <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>Edit
                                                    </a>
                                                    <a href="{% url 'student:view_individual_marks' student_name=admission.pk %}" class="btn btn-labeled btn-primary mb-2 mr-1">
                                                        <span class="btn-label"><i class="glyphicon glyphicon-eye-open"></i></span>View
                                                    </a>
                                                    
                                                    <a href="{% url 'student:admission_delete' pk=admission.pk %}" class="btn btn-labeled btn-warning mb-2 mr-1">
                                                        <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>Delete
                                                    </a>
                                              
                                                </td>
                                            </tr>
                                       {% endfor %}

                                      </tbody>

                                  </table>
                              </div> 
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}

templates/student/mark_distribution.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block innerlinks %}
{% include 'student/student_nav.html' %}
{% endblock %}
{% block css %}
<style>
    .marks-info{
        width: 100%;
        height: 70px;
        background: #0000002b;
        border-radius: 5px;
        /* display: none; */
        padding: 4px;
        border: solid 1px;
    }
</style>
{% endblock %}
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Marks Distribution - Next Go to <a href="{% url 'student:view_exams' %}">Exams</a> to create</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">

                               <form action="" method="POST" novalidate > 
                                   {% csrf_token %}
                                   <div class="row">
                                       <div class="col-md-3">
                                        {{form.class_name|as_crispy_field }}
                                       </div>
                                       <div class="col-md-3">
                                        {{form.subject_name|as_crispy_field }}
                                       </div>
                                       <div class="col-md-6">
                                           <div class="marks-info">
                                                Passing Marks of this subject is: <strong>(<span class="passing-marks"></span>)</strong>
                                                final Marks of this subject is: <strong>(<span class="final-marks"></span>)</strong>
                                                <br>
                                                final marks will be distrubuted into 4 section <strong>( 60% for exam)</strong>, <strong>(20% for class test)</strong>, <strong>(10% for Attendance & assignment)</strong>
                                           </div>
                                       </div>
                                    </div>
                                    <div class="row">
                                       <div class="col-md-3">
                                        {{form.exam|as_crispy_field }}
                                       </div>
                                       <div class="col-md-3">
                                        {{form.attendance|as_crispy_field }}
                                       </div>
                                       <div class="col-md-3">
                                        {{form.class_test|as_crispy_field }}
                                       </div>
                                       <div class="col-md-3">
                                        {{form.assignment|as_crispy_field }}
                                       </div>
                                    </div>

                                <input type="submit" class="btn btn-primary">
                               </form>
                               
                                <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th width="10%">S-No</th>
                                              <th width="10%">Class</th>
                                              <th width="10%">Subject</th>
                                              <th width="10%">Exam</th>
                                              <th width="10%">Attendance</th>
                                              <th width="10%">Class Test</th>
                                              <th width="10%">Assignment</th>
                                              <th width="20%">Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       {% for data in markdist %}
                                        <tr>
                                            <td> {{ forloop.counter }} </td>
                                            <td> {{ data.class_name }} </td>
                                            <td> {{ data.subject_name }} </td>
                                            <td> {{ data.exam }} </td>
                                            <td> {{ data.attendance }} </td>
                                            <td> {{ data.class_test }} </td>
                                            <td> {{ data.assignment }} </td>
                                            <td> 
                                                <a href="{% url 'student:mark_distribution_update' pk=data.pk %}" class="btn btn-labeled btn-success mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>Edit
                                                </a>
                                                <a href="{% url 'student:mark_distribution_delete' pk=data.pk %}" class="btn btn-labeled btn-warning mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>Delete
                                                </a>
                                               
                                            </td>
                                        </tr>
                                        {% endfor %}
                                      </tbody>

                                  </table>
                              </div>
                            </div>
                        </div>
                        <span id="get_subject_by_class" style="display: none;">{% url 'student:get_subject_by_class' %}</span>
                    </div><!--/.body content-->
{% endblock %}
{% block js %}
<script>
    $(document).ready(function(){
        $('#id_class_name').change(function(){
            var subject_id = 0;
            var url = $('#get_subject_by_class').text();       
            $.ajax({ // GETTING SECTION BY CLASS
                url: url,
                type: 'GET',
                data: {class_name:$(this).children('option:selected').val()},
                success:function(data){
                    array = []
                    $.each(data.data, function(data, item){
                        array.push('<option value="'+item.id+'">'+item.name+'</option>')
                    })
                    $('#id_subject_name').html(array);
                }

            });
           
           setTimeout(() => {             
            $.ajax({
                url: "{% url 'student:get_already_marks' %}",
                type: 'GET',
                data: {class_name:$(this).children('option:selected').val(), subject_name:$('#id_subject_name').children('option:selected').val()},
                success: function(response){
                    if(response.exam!=undefined){
                        document.getElementById('id_exam').value=response.exam
                    }else{
                        document.getElementById('id_exam').value=''
                    }
                    if(response.attendance!=undefined){
                        document.getElementById('id_attendance').value=response.attendance
                    }else{
                        document.getElementById('id_attendance').value=''
                    }
                    if(response.class_test!=undefined){
                        document.getElementById('id_class_test').value=response.class_test
                    }else{
                        document.getElementById('id_class_test').value=''
                    }
                    if(response.assignment!=undefined){
                        document.getElementById('id_assignment').value=response.assignment
                    }else{
                        document.getElementById('id_assignment').value=''
                    }
                    $('.marks-info').css('display','block');
                    $('.passing-marks').text(response.passing_marks)
                    $('.final-marks').text(response.final_marks)
                }
            });
           }, 500);
        });


    });
</script>
{% endblock %}