fee/urls.py
from django.urls import path
from .views import (
        GenerateChallan,
        UnpaidChallan,
        generated_challan,
        payChallan,
        fee_defaulter,
        fee_main,
        fee_received
    )


app_name = 'fee'
urlpatterns = [
    path('', fee_main, name="fee_main"),
    path('generatechallan', GenerateChallan, name='generate_challan'),
    path('generatedChallan', generated_challan, name='generated_challan'),
    path('unpaidChallan/', UnpaidChallan, name='unpaid_challan'),
    path('payChallan', payChallan, name='pay_challan'),
    path('FR/<str:date>/fee_received', fee_received, name='fee_received'),  
    path('feedefaulter', fee_defaulter, name='fee_defaulter'),
]

intelexcel_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

app_name = 'main'

urlpatterns = [
    path('backend/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('fee/', include('fee.urls')),
    path('academic/', include('academic.urls')),
    path('account/', include('account.urls')),
    path('messages/', include('message.urls')),
    path('payroll/', include('payroll.urls')),
    path('', include('frontend_home.urls')),
    path('student_dashboard/', include('student_dashboard.urls')),
    path('website_setting/', include('websitesetting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.urls import path
from .views import (
        TeacherCreate,
        TeacherView, 
        TeacherUpdate, 
        TeacherDelete,
        manage_salary,
        salary_monthly_detail,
        salary_detail_one,
        SchedualView,
        SchedualCreate,
        SchedualUpdate,
        SchedualDelete,
        PositionView,
        PositionCreate,
        PositionUpdate,
        PositionDelete,
        LeaveView,
        LeaveCreate,
        LeaveUpdate,
        LeaveDelete,
        employee_attendance,
        EmployeeAttednaceCreate,
        EmployeeAttednaceUpdate,
        employee_induigual,
        AdvanceSalaryView,
        AdvanceSalaryCreate,
        AdvanceSalaryUpdate,
        AdvanceSalaryDelete

    )


app_name = 'payroll'
urlpatterns = [
    path('',manage_salary , name="main_payroll"),

    path('advancesalary/view', AdvanceSalaryView.as_view(), name='advancesalary_view'),
    path('advancesalary/create', AdvanceSalaryCreate.as_view(), name='advancesalary_create'),
    path('advancesalary/<int:pk>/update', AdvanceSalaryUpdate.as_view(), name='advancesalary_update'),
    path('advancesalary/<int:pk>/delete', AdvanceSalaryDelete.as_view(), name='advancesalary_delete'),

    path('attendance/view', employee_attendance, name="employee_attendance"),
    path('attendance/<int:pk>/view', employee_induigual, name="employee_induigual"),
    path('attendance/add', EmployeeAttednaceCreate.as_view(), name="employee_attendance_add"),
    path('attendance/<int:pk>/edit', EmployeeAttednaceUpdate.as_view(), name="employee_attendance_update"),

    path('schedual/view', SchedualView.as_view(), name='schedual_view'),
    path('schedual/create', SchedualCreate.as_view(), name='schedual_create'),
    path('schedual/<int:pk>/update', SchedualUpdate.as_view(), name='schedual_update'),
    path('schedual/<int:pk>/delete', SchedualDelete.as_view(), name='schedual_delete'),

    path('position/view', PositionView.as_view(), name='position_view'),
    path('position/create', PositionCreate.as_view(), name='position_create'),
    path('position/<int:pk>/update', PositionUpdate.as_view(), name='position_update'),
    path('position/<int:pk>/delete', PositionDelete.as_view(), name='position_delete'),

    path('leave/view', LeaveView.as_view(), name='leave_view'),
    path('leave/create', LeaveCreate.as_view(), name='leave_create'),
    path('leave/<int:pk>/update', LeaveUpdate.as_view(), name='leave_update'),
    path('leave/<int:pk>/delete', LeaveDelete.as_view(), name='leave_delete'),

    path('teacher/view', TeacherView.as_view(), name='teacher_view'),
    path('teacher/create', TeacherCreate.as_view(), name='teacher_create'),
    path('teacher/<int:pk>/update', TeacherUpdate.as_view(), name='teacher_update'),
    path('teacher/<int:pk>/delete', TeacherDelete.as_view(), name='teacher_delete'),
    path('salary/', manage_salary, name='salary'),
    path('salary/<str:date>/monthly_detail',salary_monthly_detail, name='salary_monthly_detail' ),    
    path('salary/<int:pk>/<int:teacher_name_id>/monthly_detail_self',salary_detail_one, name='salary_detail_one' ),
  
]

payroll/models.py
from django.db import models
from django.contrib.auth.models import  User
from django.utils import timezone
from django.urls import reverse_lazy
# Create your models here.

gender = [
    ('Male', 'Male'), ('Female', 'Female')
]

payment_method = [
    ('Cash', 'Cash'),
     ('Cheque', 'Cheque')
]


class Schedual(models.Model):
    time_in = models.CharField(max_length=10)
    time_out = models.CharField(max_length=10)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        db_table = 'schedual'

    def __str__(self):
        return self.time_in+' to '+self.time_out

    def get_absolute_url(self):
        return reverse_lazy('payroll:schedual_view')


class Position(models.Model):
    position_title = models.CharField(max_length=50)
    rate_per_hour = models.IntegerField()
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        db_table = 'position'

    def __str__(self):
        return self.position_title

    def get_absolute_url(self):
        return reverse_lazy('payroll:position_view')


class Teacher(User):
    designation = models.CharField('Role', max_length=70)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=70, choices=gender, default='Male')
    religion = models.CharField(max_length=70, default='not mentioned')
    Phone = models.CharField(max_length=20)
    address = models.TextField()
    date_of_join = models.DateField()
    status = models.IntegerField(default=1)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, related_name='position_with_teacher')
    time_schedual = models.ForeignKey(Schedual, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='teachers', default='noimage.png')
    twitter = models.CharField(max_length=255, default='https://twitter.com/intelexcel')
    linkedin = models.CharField(max_length=255, default='https://linkedin.com/intel3xcel')
    facebook = models.CharField(max_length=255, default='https://facebook.com/intelexcel')
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))
    
    class Meta:
        ordering = ['-id']
        db_table = 'teacher'

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse_lazy('payroll:teacher_view')

class Leave(models.Model):
    employee = models.ForeignKey(Teacher, on_delete=models.CASCADE, default=0)
    date = models.DateField('Current Date')
    type = models.CharField(choices=[('h', 'Holiday'), ('l', 'Leave')], default='l', max_length=8)
    from_date = models.DateField()
    to_date = models.DateField()
    is_paid = models.BooleanField(default=1)
    reasion = models.CharField(max_length=50)
    leave_message = models.TextField()
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        db_table = 'leave'

    def __str__(self):
        return str(self.employee)

    def get_absolute_url(self):
        return reverse_lazy('payroll:leave_view')

    
class Salary(models.Model):
    employee_name = models.ForeignKey(Teacher, related_name='teacher_salary', on_delete=models.CASCADE)
    Salary_date = models.DateField()
    Salary_release_date = models.DateField()
    salary = models.IntegerField()
    bonus = models.IntegerField()
    other = models.IntegerField(default=0)
    advance_detected = models.IntegerField(default=0)
    details = models.CharField(max_length=255, default='No Message')
    payment_method = models.CharField(max_length=8, default='Cash', choices=payment_method)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        get_latest_by = 'pk'
        db_table = 'salary'

    def get_absolute_url(self):
        return reverse_lazy('payroll:fee_main')

class AdvanceSalary(models.Model):
    employee_name = models.ForeignKey(Teacher, related_name='advancesalary', on_delete=models.CASCADE)
    advance_amount = models.IntegerField()
    payment_date = models.DateField()
    monthly_detection = models.IntegerField(default=0)
    detail = models.TextField()
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        get_latest_by = 'pk'
        db_table = 'advancesalary'

    def get_absolute_url(self):
        return reverse_lazy('payroll:advancesalary_view')



class EmployeeAttendance(models.Model):
    employee_name = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    date = models.DateField()
    time_in = models.CharField(max_length=10)
    time_out = models.CharField(max_length=10)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        get_latest_by = 'pk'
        db_table = 'employeeattendance'

    def get_absolute_url(self):
        return reverse_lazy('payroll:employee_attendance')

payroll/forms.py
from django import forms
from .models import Teacher, Salary, EmployeeAttendance, Schedual
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone

class FeeDefSerchForm(forms.Form):

    seacher_date = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class': 'date seacher_date',
                'value': timezone.now().strftime('%Y-%m-%d')
            }
        )
    )


class SalaryForm(forms.ModelForm):
    class Meta:
        model = Salary
        fields = [
            'employee_name',
            'Salary_date',
            'Salary_release_date',
            'salary',
            'payment_method',
            'advance_detected',
            'bonus',
            'other',
            'details'
        ]

class TeacherForm(UserCreationForm):
    class Meta:
        model = Teacher
        fields = [
        'first_name',
        'last_name',
        'date_of_birth',
        'religion',
        'Phone',
        'designation',
        'date_of_join',
        'photo',
        'gender',
        'position',
        'time_schedual',
        'address',
        'email',
        'username',
        'password1',
        'password2'
        # 'password1'
    ]


class EmployeeAttendanceForm(forms.ModelForm):

    # def __init__(self, user, *args, **kwargs):
    #     employee_name = 

    class Meta:
        model = EmployeeAttendance
        fields = [
            'employee_name',
            'date',
            'time_in',
            'time_out',
        ]

class SchedualForm(forms.ModelForm):
    """
    docstring
    """
    class Meta:
        model = Schedual
        fields = [
            'time_in',
            'time_out'
        ]

templates/payroll/pay_salary.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block innerlinks %}
{% include 'payroll/payroll_nav.html' %}
{% endblock %} 
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">
                                            Employee Salary Payment |
                                            
                                                <a href="{% url 'payroll:salary_monthly_detail' date=current_month_redirect %}">
                                                    <u style="color: black;"> 
                                                    Check Previous Released Salary
                                                </u>
                                                </a>
                                            
                                            <!-- <a href="{% url 'payroll:salary_monthly_detail' date=current_month_redirect %} " style="color: #fc4008;"> <i class="typcn typcn-folder-open"></i> Check Previous Released Salary </a> -->
                                        </h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body"> 
                                <code>Note:</code>
                                <code> Salary will be count as employee attendance. total salary will be divided into total working hourse.  </code>    
                            <form action="" method="POST" id="submit_form">
                                {% csrf_token %}
                                 <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th width="5%">all <input type="checkbox" checked class="yes_salary_top"></th>
                                              <th width="10%">Status</th>
                                              <th width="10%">Advance History</th>
                                              <th width="10%">Name</th>
                                              <th width="5%">Detection</th>
                                              <th width="10%">Salaey</th>
                                              <th width="5%">P-M</th>
                                              <th width="10%">Date of Salary</th>
                                              <th width="10%">Release Date</th>
                                              <th width="5%">Bonus</th>
                                              <th width="5%">other</th>
                                              <th width="20%">Details</th>
                                              <th width="10%">Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       
                                       {% for salary in employee_form_data %}
                                           <tr>
                                             <td><input type="checkbox" value="{{forloop.counter}}" checked name="yes_salary" class="yes_salary"></td>
                                             <td> {% if salary.status > 0 %} <span class="btn btn-success btn-labeled" >Rs. {{salary.status}}</span> {% else %} <span class="btn btn-danger btn-labeled" >Not Paid</span> {% endif %} </td>
                                             <td> {% if salary.advance_taken.total_advance  %}  Advance: <code> {{salary.advance_taken.total_advance}} </code> <br> Returned: <code> {{salary.advance_retured.detected_amount}} </code> <br> Remaining: <code> {{salary.still_remaining}} </code>,   {% else %} No Advance  {% endif %} </td>
                                          
                                             <td> {{ salary.salaryform.employee_name }} </td>
                                             <td> {{ salary.salaryform.advance_detected }} </td>
                                             <td> {{ salary.salaryform.salary }} </td>
                                             <td> {{ salary.salaryform.payment_method }} </td>
                                             <td> {{ salary.salaryform.Salary_date }} </td>
                                             <td> {{ salary.salaryform.Salary_release_date }} </td>
                                             <td> {{ salary.salaryform.bonus }} </td>
                                             <td> {{ salary.salaryform.other }} </td>
                                             <td> {{ salary.salaryform.details }} </td>
                                             <td> 
                                                <a href="{% url 'payroll:salary_detail_one' pk=salary.salary_pk teacher_name_id=salary.pk %}" class=""> 
                                                    <i class="typcn typcn-edit"></i> Pay
                                                </a>
                                                <br>
                                                <a href="{% url 'payroll:teacher_update' pk=salary.pk %}" class=""> 
                                                   <i class="typcn typcn-edit"></i> Edit
                                               </a>
                                             </td>
                                           </tr>
                                       {% endfor %}

                                      </tbody>

                                  </table>
                                  <input type="submit" value="Quick Pay" class="btn btn-success">
                              </div>
                              
                            </form>   
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}
{% block js %}
<script>
$(document).ready(function(){
    $('.yes_salary_top').change(function(){
        if($(this).is(':checked')){
            $('.yes_salary').prop('checked', true);
        }else{
            
            $('.yes_salary').prop('checked', false);
        }
        
    });

    $('#submit_form').submit(function(){
        return confirm(" if there is a paid status. it will be update as amount\n of given field in Salary \n if you dont want to update paid or some spacefic fild or row\n please uncheck them to keep old data ")
    });
});
</script>
{% endblock %}

templates/payroll/payroll_nav.html

<style>
    .nav-design {
        border-right: 1px solid;
        padding: 7px 12px 5px 12px;
        background: #1c1f22;
        /* margin: 5px; */
    }
    .nav-design a{
        color: white;
    }
    .nav-design:hover{
        background: brown;
        color: brown;
        content: 'sdasdsd';
    }
  
    .selected-nav{
        background: brown;
        color: brown;
    }
  
</style>

<nav aria-label="breadcrumb" class="col-12 order-sm-last ">
    <ol class="breadcrumb d-inline-flex font-weight-600 fs-13 bg-white mb-0" style="width: 100%; background-color: #1c1f22 !important; padding: 0;">
   
        {% url 'payroll:main_payroll' as main_payroll %}
        {% url 'payroll:salary_monthly_detail' as salary_monthly_detail %}
        <li class="nav-design {% if request.path == main_payroll or request.path == salary_monthly_detail  %} selected-nav {% endif %}">
            <a href="{% url 'payroll:main_payroll'%}">
                All (home)
            </a>
        </li>
        {% url 'payroll:schedual_view' as schedual_view %}
        <li class="nav-design {% if request.path == schedual_view %} selected-nav {% endif %}">
            <a href="{% url 'payroll:schedual_view' %}">
                Time Schedule
            </a>
        </li>
        {% url 'payroll:position_view' as position_view %}
        <li class="nav-design {% if request.path == position_view %} selected-nav {% endif %}">
            <a href="{% url 'payroll:position_view'%}">
                Positions
            </a>         
        </li>
        {% url 'payroll:teacher_view' as teacher_view %}
        <li class="nav-design {% if request.path == teacher_view %} selected-nav {% endif %}">
            <a href="{% url 'payroll:teacher_view' %}">
                Employee
            </a>
        </li>
        {% url 'payroll:leave_view' as leave_view %}
        <li class="nav-design {% if request.path == leave_view %} selected-nav {% endif %}">
            <a href="{% url 'payroll:leave_view'%}">
                Leave
            </a>
        </li>
        {% url 'payroll:employee_attendance' as employee_attendance %}
        <li class="nav-design {% if request.path == employee_attendance %} selected-nav {% endif %}">
            <a href="{% url 'payroll:employee_attendance'%}">
                Attendance
            </a>
        </li>
        {% url 'payroll:advancesalary_view' as advancesalary_view %}
        <li class="nav-design {% if request.path == advancesalary_view %} selected-nav {% endif %}">
            <a href="{% url 'payroll:advancesalary_view'%}">
                Advance Salary
            </a>
        </li>
        {% url 'payroll:salary' as salary %}
        <li class="nav-design {% if request.path == salary %} selected-nav {% endif %}">
            <a href="{% url 'payroll:salary'%}">
                Employee Salary
            </a>
        </li>
    </ol>
</nav>


















templates/payroll/position.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block innerlinks %}
{% include 'payroll/payroll_nav.html' %}
{% endblock %}
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">List of positions</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'payroll:position_create' %}" class="btn btn-primary">Add New</a>
                                <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th width="10%">S-No</th>
                                              <th width="30%">Position Title</th>
                                              <th width="40%">Rate Per Hour</th>
                                              <th width="20%">Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       
                                       {% for position in positions %}
                                        <tr>
                                            <td> {{forloop.counter}} </td>
                                            <td> {{ position.position_title }} </td>
                                            <td> {{ position.rate_per_hour }} </td>
                                            <td>
                                                <a href="{% url 'payroll:position_update' pk=position.pk %}" class="btn btn-labeled btn-success mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>Edit
                                                </a>
                                                <a href="{% url 'payroll:position_delete' pk=position.pk %}" class="btn btn-labeled btn-warning mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>Delete
                                                </a>
                                            </td>
                                        </tr>
                                       {% endfor %}

                                      </tbody>

                                  </table>
                              </div>
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}

templates/payroll/schedual.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% block innerlinks %}
{% include 'payroll/payroll_nav.html' %}
{% endblock %}
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">List of time Scheduals</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'payroll:schedual_create' %}" class="btn btn-primary">Add New</a>
                                <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th width="10%">S-No</th>
                                              <th width="30%">Time In</th>
                                              <th width="40%">Time Out</th>
                                              <th width="20%">Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       
                                       {% for schedual in scheduals %}
                                        <tr>
                                            <td> {{forloop.counter}} </td>
                                            <td> {{ schedual.time_in }} </td>
                                            <td> {{ schedual.time_out }} </td>
                                            <td>
                                                <a href="{% url 'payroll:schedual_update' pk=schedual.pk %}" class="btn btn-labeled btn-success mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-pencil"></i></span>Edit
                                                </a>
                                                <a href="{% url 'payroll:schedual_delete' pk=schedual.pk %}" class="btn btn-labeled btn-warning mb-2 mr-1">
                                                    <span class="btn-label"><i class="glyphicon glyphicon-remove"></i></span>Delete
                                                </a>
                                            </td>
                                        </tr>
                                       {% endfor %}

                                      </tbody>

                                  </table>
                              </div>
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}