academic/urls.py
from django.urls import path
from .views import (
    ClassesView,
    ClassesCreate,
    ClassesUpdate,
    ClassesDelete,
    RoomView,
    RoomCreate,
    RoomUpdate,
    RoomDelete,
    SubjectView,
    SubjectCreate,
    SubjectUpdate,
    SubjectDelete,
    RoutineView,
    RoutineCreate,
    RoutineUpdate,
    RoutineDelete,
    AcademicView,
    get_section_by_class
    
)


app_name = 'academic'
urlpatterns = [
    path('', AcademicView, name='academic_main'),
    path('classes/view', ClassesView.as_view(), name='classes_view'),
    path('classes/create', ClassesCreate.as_view(), name='classes_create'),
    path('classes/<int:pk>/update', ClassesUpdate.as_view(), name='classes_update'),
    path('classes/<int:pk>/delete', ClassesDelete.as_view(), name='classes_delete'),
    path('room/view', RoomView.as_view(), name='room_view'),
    path('room/create', RoomCreate.as_view(), name='room_create'),
    path('room/<int:pk>/update', RoomUpdate.as_view(), name='room_update'),
    path('room/<int:pk>/delete', RoomDelete.as_view(), name='room_delete'),
    path('subject/view', SubjectView.as_view(), name='subject_view'),
    path('subject/create', SubjectCreate.as_view(), name='subject_create'),
    path('subject/<int:pk>/update', SubjectUpdate.as_view(), name='subject_update'),
    path('subject/<int:pk>/delete', SubjectDelete.as_view(), name='subject_delete'),
    path('routine/view', RoutineView.as_view(), name='routine_view'),
    path('routine/create', RoutineCreate.as_view(), name='routine_create'),
    path('routine/<int:pk>/update', RoutineUpdate.as_view(), name='routine_update'),
    path('routine/<int:pk>/delete', RoutineDelete.as_view(), name='routine_delete'),
    path('get_section_by_class/', get_section_by_class, name='get_section_by_class'),

]


account/urls.py
from django.urls import path
from .views import (
    FeetypeView,
    FeetypeCreate,
    FeetypeUpdate,
    FeetypeDelete,
    InvoiceDetailView,
    InvoiceDetailCreate,
    InvoiceDetailUpdate,
    InvoiceDetailDelete,
    ExpenseView,
    ExpenseCreate,
    ExpenseUpdate,
    ExpenseDelete,
    IncomeView,
    IncomeCreate,
    IncomeUpdate,
    IncomeDelete,
    get_income_with_ajax,
    get_expense_with_ajax
)

app_name = 'account'
urlpatterns = [
    path('feetype/view', FeetypeView.as_view(), name='feetype_view'),
    path('feetype/create', FeetypeCreate.as_view(), name='feetype_create'),
    path('feetype/<int:pk>/update', FeetypeUpdate.as_view(), name='feetype_update'),
    path('feetype/<int:pk>/view', FeetypeDelete.as_view(), name='feetype_delete'),
    path('invoice/view', InvoiceDetailView.as_view(), name='invoice_view'),
    path('invoice/create', InvoiceDetailCreate.as_view(), name='invoice_create'),
    path('invoice/<int:pk>/update', InvoiceDetailUpdate.as_view(), name='invoice_update'),
    path('invoice/<int:pk>/view', InvoiceDetailDelete.as_view(), name='invoice_delete'),
    path('expense/view', ExpenseView.as_view(), name='expense_view'),
    path('expense/create', ExpenseCreate.as_view(), name='expense_create'),
    path('expense/<int:pk>/update', ExpenseUpdate.as_view(), name='expense_update'),
    path('expense/<int:pk>/view', ExpenseDelete.as_view(), name='expense_delete'),
    path('income/view', IncomeView.as_view(), name='income_view'),
    path('income/create', IncomeCreate.as_view(), name='income_create'),
    path('income/<int:pk>/update', IncomeUpdate.as_view(), name='income_update'),
    path('income/<int:pk>/view', IncomeDelete.as_view(), name='income_delete'),
    path('get_income_with_ajax', get_income_with_ajax, name="get_income_with_ajax"),
    path('get_expense_with_ajax', get_expense_with_ajax, name="get_expense_with_ajax")
]

fee/urls.py
from django.urls import path
from .views import (
        GenerateChallan,
        UnpaidChallan,
        generated_challan,
        payChallan,
        fee_defaulter,
        fee_main,
        fee_received
    )


app_name = 'fee'
urlpatterns = [
    path('', fee_main, name="fee_main"),
    path('generatechallan', GenerateChallan, name='generate_challan'),
    path('generatedChallan', generated_challan, name='generated_challan'),
    path('unpaidChallan/', UnpaidChallan, name='unpaid_challan'),
    path('payChallan', payChallan, name='pay_challan'),
    path('FR/<str:date>/fee_received', fee_received, name='fee_received'),  
    path('feedefaulter', fee_defaulter, name='fee_defaulter'),
]

intelexcel_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

app_name = 'main'

urlpatterns = [
    path('backend/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('fee/', include('fee.urls')),
    path('academic/', include('academic.urls')),
    path('account/', include('account.urls')),
    path('messages/', include('message.urls')),
    path('payroll/', include('payroll.urls')),
    path('', include('frontend_home.urls')),
    path('student_dashboard/', include('student_dashboard.urls')),
    path('website_setting/', include('websitesetting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.urls import path
from .views import (
        TeacherCreate,
        TeacherView, 
        TeacherUpdate, 
        TeacherDelete,
        manage_salary,
        salary_monthly_detail,
        salary_detail_one,
        SchedualView,
        SchedualCreate,
        SchedualUpdate,
        SchedualDelete,
        PositionView,
        PositionCreate,
        PositionUpdate,
        PositionDelete,
        LeaveView,
        LeaveCreate,
        LeaveUpdate,
        LeaveDelete,
        employee_attendance,
        EmployeeAttednaceCreate,
        EmployeeAttednaceUpdate,
        employee_induigual,
        AdvanceSalaryView,
        AdvanceSalaryCreate,
        AdvanceSalaryUpdate,
        AdvanceSalaryDelete

    )


app_name = 'payroll'
urlpatterns = [
    path('',manage_salary , name="main_payroll"),

    path('advancesalary/view', AdvanceSalaryView.as_view(), name='advancesalary_view'),
    path('advancesalary/create', AdvanceSalaryCreate.as_view(), name='advancesalary_create'),
    path('advancesalary/<int:pk>/update', AdvanceSalaryUpdate.as_view(), name='advancesalary_update'),
    path('advancesalary/<int:pk>/delete', AdvanceSalaryDelete.as_view(), name='advancesalary_delete'),

    path('attendance/view', employee_attendance, name="employee_attendance"),
    path('attendance/<int:pk>/view', employee_induigual, name="employee_induigual"),
    path('attendance/add', EmployeeAttednaceCreate.as_view(), name="employee_attendance_add"),
    path('attendance/<int:pk>/edit', EmployeeAttednaceUpdate.as_view(), name="employee_attendance_update"),

    path('schedual/view', SchedualView.as_view(), name='schedual_view'),
    path('schedual/create', SchedualCreate.as_view(), name='schedual_create'),
    path('schedual/<int:pk>/update', SchedualUpdate.as_view(), name='schedual_update'),
    path('schedual/<int:pk>/delete', SchedualDelete.as_view(), name='schedual_delete'),

    path('position/view', PositionView.as_view(), name='position_view'),
    path('position/create', PositionCreate.as_view(), name='position_create'),
    path('position/<int:pk>/update', PositionUpdate.as_view(), name='position_update'),
    path('position/<int:pk>/delete', PositionDelete.as_view(), name='position_delete'),

    path('leave/view', LeaveView.as_view(), name='leave_view'),
    path('leave/create', LeaveCreate.as_view(), name='leave_create'),
    path('leave/<int:pk>/update', LeaveUpdate.as_view(), name='leave_update'),
    path('leave/<int:pk>/delete', LeaveDelete.as_view(), name='leave_delete'),

    path('teacher/view', TeacherView.as_view(), name='teacher_view'),
    path('teacher/create', TeacherCreate.as_view(), name='teacher_create'),
    path('teacher/<int:pk>/update', TeacherUpdate.as_view(), name='teacher_update'),
    path('teacher/<int:pk>/delete', TeacherDelete.as_view(), name='teacher_delete'),
    path('salary/', manage_salary, name='salary'),
    path('salary/<str:date>/monthly_detail',salary_monthly_detail, name='salary_monthly_detail' ),    
    path('salary/<int:pk>/<int:teacher_name_id>/monthly_detail_self',salary_detail_one, name='salary_detail_one' ),
  
]

student/urls.py

from django.urls import path
from academic.views import SectionCreate, SectionUpdate,  SectionDelete
from .views import (
    StudentView,
    AttendanceMark,
    AttendanceSearch,
    AttendanceView,
    IndividualMarksView,
    AdmissionCreate, 
    AdmissionView, 
    AdmissionDelete, 
    AdmissionUpdate, 
    AdmissionDetail,
    StudentMarkSearch,
    StudentMarkCreate,
    MarkDistributionCreate,
    MarkDistributionUpdate,
    MarkDistributionDelete,
    ExamsView,
    ExamsDetail,
    ExamsCreate,
    ExamsUpdate,
    ExamsDelete,
    get_class_asignments,
    SendEmail_SaveData,
    SendEmailForExam,
    get_fee,
    get_subject_by_class,
    get_already_marks,
    getting_marks_from_calculated
    )


app_name = 'student'
urlpatterns = [
    path('', StudentView, name='student_view'),
    path('admission/create/', AdmissionCreate.as_view(), name='admission_create'),
    path('admission/view/', AdmissionView.as_view(), name='admission_view'),
    path('admission/view/<int:pk>/detail', AdmissionDetail.as_view(), name='admission_detail'),
    path('admission/view/<int:pk>/update', AdmissionUpdate.as_view(), name='admission_update'),
    path('admission/view/<int:pk>/delete', AdmissionDelete.as_view(), name='admission_delete'),
    path('createSection/', SectionCreate.as_view(), name='create_section'),
    path('updateSection/<int:pk>', SectionUpdate.as_view(), name='update_section'),
    path('deleteSection/<int:pk>/delete', SectionDelete.as_view(), name='delete_section'),
    path('viewexams/view', ExamsView.as_view(), name='view_exams'),
    path('createexams/', ExamsCreate.as_view(), name='create_exams'),
    path('detailexams/<int:pk>/detail', ExamsDetail.as_view(), name='detail_exams'),
    path('updateexams/<int:pk>/edit', ExamsUpdate.as_view(), name='update_exams'),
    path('deleteexams/<int:pk>/delete', ExamsDelete.as_view(), name='delete_exams'),
    path('SendEmail_SaveData/', SendEmail_SaveData, name='SendEmail_SaveData'),
    path('sendemailforexam/', SendEmailForExam.as_view(), name='sendemailforexam'),
    path('attendance/view', AttendanceView.as_view(), name='attendance_view'),
    path('attendance/search', AttendanceSearch.as_view(), name='attendance_search'),
    path('attendance/mark', AttendanceMark.as_view(), name='attendance_mark'),
    path('student_mark/search', StudentMarkSearch.as_view(), name='student_mark'),
    path('student_mark/add', StudentMarkCreate.as_view(), name='student_mark_add'),
    path('mark_distribution/create', MarkDistributionCreate.as_view(), name='mark_distribution_create'),
    path('mark_distribution/<int:pk>/update', MarkDistributionUpdate.as_view(), name='mark_distribution_update'),
    path('mark_distribution/<int:pk>/delete', MarkDistributionDelete.as_view(), name='mark_distribution_delete'),
    path('report/<int:student_name>/info', IndividualMarksView.as_view(), name='view_individual_marks'),    
    path('report/<int:student_name>/info?year&tab', IndividualMarksView.as_view(), name='view_individual_marks2'),    
    path('get_fee', get_fee, name="get_fee"),
    path('get_subject_by_class/', get_subject_by_class , name="get_subject_by_class"),
    path('get_already_marks/', get_already_marks , name="get_already_marks"),
    path('get_class_asignments/<int:pk>/class/<int:class_name>/subject/<int:subject>', get_class_asignments , name="get_class_asignments"),
    path('getting_marks_from_calculated/', getting_marks_from_calculated , name="getting_marks_from_calculated")
]

fee/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy
from student.models import Admission
from academic.models import Section, Classes
# Create your models here.

payment_method = [
    ('Cash', 'Cash'),
     ('Cheque', 'Cheque')
]


        

class Voucher(models.Model):
    reg_number = models.CharField(max_length=25)
    student_name = models.ForeignKey(Admission, on_delete=models.CASCADE)
    father_name = models.CharField(max_length=25)
    issue_date = models.DateField()
    due_date = models.DateField()
    fee_month = models.CharField(max_length=50)
    year = models.CharField(max_length=10)
    month = models.CharField(max_length=10)
    monthly_tution_fee = models.IntegerField()
    monthly_tution_fee_paid = models.IntegerField(default=0)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    class_name = models.ForeignKey(Classes, on_delete=models.CASCADE)
    challan_number = models.CharField(max_length=10)
    module_holder = models.CharField(max_length=50)
    inserted_date = models.DateField(auto_now=timezone.now().strftime('%Y-%m-%d'))

    class Meta:
        ordering = ['-id']
        db_table = 'voucher'

    def get_absolute_url(self):
        return reverse_lazy('fee:generated_challan')
    

fee/forms.py
from django import forms
from student.models import Admission, Classes, Section
from django.utils import timezone
import datetime


years = []

current_year = timezone.now().strftime("%Y")

for i in range(2005, int(current_year)+2):
    years.append(
        (i, i)
    )



class SearchChallan(forms.Form):

    def __init__(self, user, *args, **kwargs):
        super(SearchChallan, self).__init__(*args, **kwargs)
        # self.fields['class_name'].widget.attrs={'class': 'basic-multiple'}
        self.fields['classes'].widget.attrs={'class': 'basic-multiple'}
        self.fields['admission_section'].widget.attrs={'class': 'basic-multiple'}
        self.fields['classes'].queryset = Classes.objects.filter(module_holder=user)
        self.fields['admission_section'].queryset = Section.objects.filter(module_holder=user)

    issue_date = forms.DateField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'date',
            'value': timezone.now().strftime('%Y-%m-%d')
        }
    ))
    due_date = forms.DateField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'date',
            'value': (timezone.now()+datetime.timedelta(7)).strftime('%Y-%m-%d')
        }
    ))
    fee_month = forms.CharField(max_length=50 ,required=False, widget=forms.TextInput(
        attrs={
            'type': 'month',
            'value': timezone.now().strftime('%Y-%m')
        }
    ))
    year = forms.ChoiceField(choices=years, widget=forms.Select(
        attrs = {
            'class': 'year',
            'value': timezone.now().strftime('%Y')
        }
    ))
    classes = forms.ModelChoiceField(queryset=Classes.objects.all())
    admission_section = forms.ModelChoiceField(queryset=Section.objects.all())
   

templates/fee/fee_nav.html
<style>
    .nav-design {
        border-right: 1px solid;
        padding: 7px 12px 5px 12px;
        background: #1c1f22;
        /* margin: 5px; */
    }
    .nav-design a{
        color: white;
    }
    .nav-design:hover{
        background: brown;
        color: brown;
        content: 'sdasdsd';
    }
  
    .selected-nav{
        background: brown;
        color: brown;
    }
  
</style>

<nav aria-label="breadcrumb" class="col-12 order-sm-last ">
    <ol class="breadcrumb d-inline-flex font-weight-600 fs-13 bg-white mb-0" style="width: 100%; background-color: #1c1f22 !important; padding: 0;">
   
        {% url 'fee:fee_main' as fee_main %}
        <li class="nav-design {% if request.path == fee_main %} selected-nav {% endif %}">
            <a href="{% url 'fee:fee_main'%}" >
                All (home)
             </a>
        </li>
        {% url 'fee:generate_challan' as generate_challan %}
        <li class="nav-design {% if request.path == generate_challan %} selected-nav {% endif %}">
            <a href="{% url 'fee:generate_challan'%}" >
                Generate Challan
            </a>
        </li>
        {% url 'fee:unpaid_challan' as unpaid_challan %}
        <li class="nav-design {% if request.path == unpaid_challan %} selected-nav {% endif %}">
            <a href="{% url 'fee:unpaid_challan'%}" >
                Pay Challan</a> 
            </a>            
        </li>
        {% url 'fee:fee_defaulter' as fee_defaulter %}
        <li class="nav-design {% if request.path == fee_defaulter %} selected-nav {% endif %}">
            <a href="{% url 'fee:fee_defaulter'%}" >
                Fee Defaulters
            </a>
        </li>
        {% url 'account:expense_view' as expense_view %}
        <li class="nav-design {% if request.path == expense_view %} selected-nav {% endif %}">
            <a href="{% url 'account:expense_view'%}" >
                Expense Info
            </a>
        </li>
        {% url 'account:income_view' as income_view %}
        <li class="nav-design {% if request.path == income_view %} selected-nav {% endif %}">
            <a href="{% url 'account:income_view'%}"  >
                Income Info
            </a> 
        </li>




    </ol>
</nav>

templates/fee/income.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block innerlinks %}
{% include 'fee/fee_nav.html' %}
{% endblock %}
{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">All Expenses</h6>
                                        <p id="fee_data" style="display:none ;">{{fee_data}}</p>
                                        <p id="income_data" style="display: none;">{{income_data}}</p>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <a href="{% url 'account:income_create' %}" class="btn btn-primary">add new</a>
                                <hr>
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-3 offset-3">
                                         {{search_form|crispy}}
                                        </div>
                                        <div class="col-md-3">
                                         <div id="div_id_date" class="form-group"> 
                                             <label for="id_date" class=" requiredField">
                                                  <span class="asteriskField">&nbsp</span> 
                                             </label> 
                                             <div class=""> 
                                                 <input type="submit"  value="Search" class="mx-4 btn btn-success">
                                             </div>
                                         </div>
                                         
                                        
                                        </div>
                                    </div>                                    
                                </form>
                                <div class="table-responsive my-4">
                                    
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th>S-No</th>
                                              <th>Name</th>
                                              <th>Date</th>
                                              <th>File</th>
                                              <th>Note</th>
                                              <th>Action</th>
                                          </tr>
                                      </thead>
                                      <tbody>
                                        {% for income in incomes %}
                                        <tr>
                                            <td> {{forloop.counter}} </td>
                                            <td> {{income.name}} </td>
                                            <td> {{income.date}} </td>
                                            <td> {% if income.file == 'not'  %}  No FIle {% else %} <a href="{{income.file.url}}" download="download">Download</a> {% endif %}  </td>
                                            <td> {{income.note}} </td>
                                            <td>
                                                <a href="{% url 'account:income_update' pk=income.pk %}">Edit</a> | 
                                                <a href="{% url 'account:income_delete' pk=income.pk %}">Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                      </tbody>

                                  </table>
                                  </div>
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-body">
                               
                                <div class="card mb-4">
                                    <div class="card-body">
                                        <div class="header-body mb-4 pt-0">
                                            <div class="row align-items-end">
                                                <div class="col">
                                                    <!-- Pretitle -->
                                                    <div class="row">
                                                        <div class="col-md-3">
                                                            <h6 class="header-pretitle text-muted fs-11 font-weight-bold text-uppercase mb-1">
                                                                Overview
                                                            </h6>
                                                            <!-- Title -->
                                                            <h1 class="header-title fs-21 font-weight-bold">
                                                                Performance
                                                            </h1>
                                                        </div>
                                                        <div class="col-md-3">
                                                            <select id="get_income_with_ajax" class="form-control">
                                                                <option value="2020">2020</option>
                                                                <option value="2021">2021</option>
                                                                <option value="2022">2022</option>
                                                                <option value="2023">2023</option>
                                                                <option value="2024">2024</option>
                                                                <option value="2025">2025</option>
                                                                <option value="2026">2026</option>
                                                                <option value="2027">2027</option>
                                                                <option value="2028">2028</option>
                                                            </select>
                                                            <p id="ajax_url" style="display: none;">{% url 'account:get_income_with_ajax' %}</p>
                                                        </div>
                                                        <div class="com-md-3" id="char_loader">
                                                            <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div> &nbsp;
                                                            <strong>Loading......</strong>
                                                        </div>
                                                        
                                                    </div>

                                                   
                                                </div>
                                                <div class="col-auto">
                                                    <!-- Nav -->
                                                    <ul class="nav nav-tabs header-tabs">
                                                        <li class="nav-item" >
                                                            <a href="#" id="0"  class="nav-link text-center active" data-toggle="tab">
                                                                <h6 id="student" class="header-pretitle text-muted fs-11 font-weight-bold text-uppercase mb-1">
                                                                    Students Fee
                                                                </h6>
                                                                <h3 class="mb-0 fs-16 font-weight-bold">
                                                                    Rs. <span id="total_fee">{{total_fee}}</span>
                                                                </h3>
                                                            </a>
                                                        </li>
                                                        <li class="nav-item">
                                                            <a href="#" id="1" class="nav-link text-center" data-toggle="tab">
                                                                <h6 id="expense" class="header-pretitle text-muted fs-11 font-weight-bold text-uppercase mb-1">
                                                                    Other Income
                                                                </h6>
                                                                <h3 class="mb-0 fs-16 font-weight-bold">
                                                                    Rs. <span id="total_income">{{total_income}}</span>
                                                                </h3>
                                                            </a>
                                                        </li>
                                                        <!-- <li class="nav-item">
                                                            <a href="#" id="2" class="nav-link text-center" data-toggle="tab">
                                                                <h6 class="header-pretitle text-muted fs-11 font-weight-bold text-uppercase mb-1">
                                                                    Bounce
                                                                </h6>
                                                                <h3 class="mb-0 fs-16 font-weight-bold">
                                                                    50.2%
                                                                </h3>
                                                            </a>
                                                        </li> -->
                                                    </ul>
                                                </div>
                                            </div> <!-- / .row -->
                                        </div> <!-- / .header-body -->
                                        <div class="chart">
                                            <canvas id="forecast" width="300" height="100"></canvas>
                                        </div>
                                    </div>
                                </div>
                          
                            </div>
                        </div>
                              </div>
                            </div>
                        </div>


                    </div><!--/.body content-->
{% endblock %}
{% block js %}
 <!-- Third Party Scripts(used by this page)-->
 <script src="{% static 'assets/plugins/chartJs/Chart.min.js' %}"></script>
 <!--Page Active Scripts(used by this page)-->
 <script src="{% static 'assets/plugins/chartJs/chartJs.active.js' %}"></script>
{% endblock %}