account/urls.py
from django.urls import path
from .views import (
    FeetypeView,
    FeetypeCreate,
    FeetypeUpdate,
    FeetypeDelete,
    InvoiceDetailView,
    InvoiceDetailCreate,
    InvoiceDetailUpdate,
    InvoiceDetailDelete,
    ExpenseView,
    ExpenseCreate,
    ExpenseUpdate,
    ExpenseDelete,
    IncomeView,
    IncomeCreate,
    IncomeUpdate,
    IncomeDelete,
    get_income_with_ajax,
    get_expense_with_ajax
)

app_name = 'account'
urlpatterns = [
    path('feetype/view', FeetypeView.as_view(), name='feetype_view'),
    path('feetype/create', FeetypeCreate.as_view(), name='feetype_create'),
    path('feetype/<int:pk>/update', FeetypeUpdate.as_view(), name='feetype_update'),
    path('feetype/<int:pk>/view', FeetypeDelete.as_view(), name='feetype_delete'),
    path('invoice/view', InvoiceDetailView.as_view(), name='invoice_view'),
    path('invoice/create', InvoiceDetailCreate.as_view(), name='invoice_create'),
    path('invoice/<int:pk>/update', InvoiceDetailUpdate.as_view(), name='invoice_update'),
    path('invoice/<int:pk>/view', InvoiceDetailDelete.as_view(), name='invoice_delete'),
    path('expense/view', ExpenseView.as_view(), name='expense_view'),
    path('expense/create', ExpenseCreate.as_view(), name='expense_create'),
    path('expense/<int:pk>/update', ExpenseUpdate.as_view(), name='expense_update'),
    path('expense/<int:pk>/view', ExpenseDelete.as_view(), name='expense_delete'),
    path('income/view', IncomeView.as_view(), name='income_view'),
    path('income/create', IncomeCreate.as_view(), name='income_create'),
    path('income/<int:pk>/update', IncomeUpdate.as_view(), name='income_update'),
    path('income/<int:pk>/view', IncomeDelete.as_view(), name='income_delete'),
    path('get_income_with_ajax', get_income_with_ajax, name="get_income_with_ajax"),
    path('get_expense_with_ajax', get_expense_with_ajax, name="get_expense_with_ajax")
]

fee/urls.py
from django.urls import path
from .views import (
        GenerateChallan,
        UnpaidChallan,
        generated_challan,
        payChallan,
        fee_defaulter,
        fee_main,
        fee_received
    )


app_name = 'fee'
urlpatterns = [
    path('', fee_main, name="fee_main"),
    path('generatechallan', GenerateChallan, name='generate_challan'),
    path('generatedChallan', generated_challan, name='generated_challan'),
    path('unpaidChallan/', UnpaidChallan, name='unpaid_challan'),
    path('payChallan', payChallan, name='pay_challan'),
    path('FR/<str:date>/fee_received', fee_received, name='fee_received'),  
    path('feedefaulter', fee_defaulter, name='fee_defaulter'),
]

intelexcel_sms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

app_name = 'main'

urlpatterns = [
    path('backend/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('fee/', include('fee.urls')),
    path('academic/', include('academic.urls')),
    path('account/', include('account.urls')),
    path('messages/', include('message.urls')),
    path('payroll/', include('payroll.urls')),
    path('', include('frontend_home.urls')),
    path('student_dashboard/', include('student_dashboard.urls')),
    path('website_setting/', include('websitesetting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payroll/urls.py
from django.urls import path
from .views import (
        TeacherCreate,
        TeacherView, 
        TeacherUpdate, 
        TeacherDelete,
        manage_salary,
        salary_monthly_detail,
        salary_detail_one,
        SchedualView,
        SchedualCreate,
        SchedualUpdate,
        SchedualDelete,
        PositionView,
        PositionCreate,
        PositionUpdate,
        PositionDelete,
        LeaveView,
        LeaveCreate,
        LeaveUpdate,
        LeaveDelete,
        employee_attendance,
        EmployeeAttednaceCreate,
        EmployeeAttednaceUpdate,
        employee_induigual,
        AdvanceSalaryView,
        AdvanceSalaryCreate,
        AdvanceSalaryUpdate,
        AdvanceSalaryDelete

    )


app_name = 'payroll'
urlpatterns = [
    path('',manage_salary , name="main_payroll"),

    path('advancesalary/view', AdvanceSalaryView.as_view(), name='advancesalary_view'),
    path('advancesalary/create', AdvanceSalaryCreate.as_view(), name='advancesalary_create'),
    path('advancesalary/<int:pk>/update', AdvanceSalaryUpdate.as_view(), name='advancesalary_update'),
    path('advancesalary/<int:pk>/delete', AdvanceSalaryDelete.as_view(), name='advancesalary_delete'),

    path('attendance/view', employee_attendance, name="employee_attendance"),
    path('attendance/<int:pk>/view', employee_induigual, name="employee_induigual"),
    path('attendance/add', EmployeeAttednaceCreate.as_view(), name="employee_attendance_add"),
    path('attendance/<int:pk>/edit', EmployeeAttednaceUpdate.as_view(), name="employee_attendance_update"),

    path('schedual/view', SchedualView.as_view(), name='schedual_view'),
    path('schedual/create', SchedualCreate.as_view(), name='schedual_create'),
    path('schedual/<int:pk>/update', SchedualUpdate.as_view(), name='schedual_update'),
    path('schedual/<int:pk>/delete', SchedualDelete.as_view(), name='schedual_delete'),

    path('position/view', PositionView.as_view(), name='position_view'),
    path('position/create', PositionCreate.as_view(), name='position_create'),
    path('position/<int:pk>/update', PositionUpdate.as_view(), name='position_update'),
    path('position/<int:pk>/delete', PositionDelete.as_view(), name='position_delete'),

    path('leave/view', LeaveView.as_view(), name='leave_view'),
    path('leave/create', LeaveCreate.as_view(), name='leave_create'),
    path('leave/<int:pk>/update', LeaveUpdate.as_view(), name='leave_update'),
    path('leave/<int:pk>/delete', LeaveDelete.as_view(), name='leave_delete'),

    path('teacher/view', TeacherView.as_view(), name='teacher_view'),
    path('teacher/create', TeacherCreate.as_view(), name='teacher_create'),
    path('teacher/<int:pk>/update', TeacherUpdate.as_view(), name='teacher_update'),
    path('teacher/<int:pk>/delete', TeacherDelete.as_view(), name='teacher_delete'),
    path('salary/', manage_salary, name='salary'),
    path('salary/<str:date>/monthly_detail',salary_monthly_detail, name='salary_monthly_detail' ),    
    path('salary/<int:pk>/<int:teacher_name_id>/monthly_detail_self',salary_detail_one, name='salary_detail_one' ),
  
]

student/urls.py

from django.urls import path
from academic.views import SectionCreate, SectionUpdate,  SectionDelete
from .views import (
    StudentView,
    AttendanceMark,
    AttendanceSearch,
    AttendanceView,
    IndividualMarksView,
    AdmissionCreate, 
    AdmissionView, 
    AdmissionDelete, 
    AdmissionUpdate, 
    AdmissionDetail,
    StudentMarkSearch,
    StudentMarkCreate,
    MarkDistributionCreate,
    MarkDistributionUpdate,
    MarkDistributionDelete,
    ExamsView,
    ExamsDetail,
    ExamsCreate,
    ExamsUpdate,
    ExamsDelete,
    get_class_asignments,
    SendEmail_SaveData,
    SendEmailForExam,
    get_fee,
    get_subject_by_class,
    get_already_marks,
    getting_marks_from_calculated
    )


app_name = 'student'
urlpatterns = [
    path('', StudentView, name='student_view'),
    path('admission/create/', AdmissionCreate.as_view(), name='admission_create'),
    path('admission/view/', AdmissionView.as_view(), name='admission_view'),
    path('admission/view/<int:pk>/detail', AdmissionDetail.as_view(), name='admission_detail'),
    path('admission/view/<int:pk>/update', AdmissionUpdate.as_view(), name='admission_update'),
    path('admission/view/<int:pk>/delete', AdmissionDelete.as_view(), name='admission_delete'),
    path('createSection/', SectionCreate.as_view(), name='create_section'),
    path('updateSection/<int:pk>', SectionUpdate.as_view(), name='update_section'),
    path('deleteSection/<int:pk>/delete', SectionDelete.as_view(), name='delete_section'),
    path('viewexams/view', ExamsView.as_view(), name='view_exams'),
    path('createexams/', ExamsCreate.as_view(), name='create_exams'),
    path('detailexams/<int:pk>/detail', ExamsDetail.as_view(), name='detail_exams'),
    path('updateexams/<int:pk>/edit', ExamsUpdate.as_view(), name='update_exams'),
    path('deleteexams/<int:pk>/delete', ExamsDelete.as_view(), name='delete_exams'),
    path('SendEmail_SaveData/', SendEmail_SaveData, name='SendEmail_SaveData'),
    path('sendemailforexam/', SendEmailForExam.as_view(), name='sendemailforexam'),
    path('attendance/view', AttendanceView.as_view(), name='attendance_view'),
    path('attendance/search', AttendanceSearch.as_view(), name='attendance_search'),
    path('attendance/mark', AttendanceMark.as_view(), name='attendance_mark'),
    path('student_mark/search', StudentMarkSearch.as_view(), name='student_mark'),
    path('student_mark/add', StudentMarkCreate.as_view(), name='student_mark_add'),
    path('mark_distribution/create', MarkDistributionCreate.as_view(), name='mark_distribution_create'),
    path('mark_distribution/<int:pk>/update', MarkDistributionUpdate.as_view(), name='mark_distribution_update'),
    path('mark_distribution/<int:pk>/delete', MarkDistributionDelete.as_view(), name='mark_distribution_delete'),
    path('report/<int:student_name>/info', IndividualMarksView.as_view(), name='view_individual_marks'),    
    path('report/<int:student_name>/info?year&tab', IndividualMarksView.as_view(), name='view_individual_marks2'),    
    path('get_fee', get_fee, name="get_fee"),
    path('get_subject_by_class/', get_subject_by_class , name="get_subject_by_class"),
    path('get_already_marks/', get_already_marks , name="get_already_marks"),
    path('get_class_asignments/<int:pk>/class/<int:class_name>/subject/<int:subject>', get_class_asignments , name="get_class_asignments"),
    path('getting_marks_from_calculated/', getting_marks_from_calculated , name="getting_marks_from_calculated")
]

templates/admission/admission.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Add New Student <a href="#">Impot From Excel</a></h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <form method="POST" novalidate enctype="multipart/form-data">
                                        {% csrf_token %} 
                                        <div class="row">
                                            <div class="col-md-3">
                                               
                                                {{ form.admission_date|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.admission_class|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.admission_section|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.admission_registration|as_crispy_field }}    
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3">
                                                {{ form.name_of_student|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.father_name|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.father_cnic|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.date_of_birth|as_crispy_field }}    
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3">
                                                {{ form.contact|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.annual_fund|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.cast|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.father_profession|as_crispy_field }}    
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-3">
                                                {{ form.gender|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.free_student|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.monthly_tution_fee|as_crispy_field }}    
                                            </div>
                                            <div class="col-md-3">
                                                {{ form.concession_fee|as_crispy_field }}    
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                {{ form.address|as_crispy_field }}    
                                            </div>
                                           
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                {{form.photo|as_crispy_field}}
                                            </div>
                                           
                                            <div class="col-md-6">
                                                {{form.recieve_admissin_fee_with_admission|as_crispy_field}}
                                            </div>
                                        </div>
                                        
                                        <input type="submit" value="Save Data" name="">
                                </form>
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}

templates/admission/admission_confirm_delete.html
{% extends 'master.html' %}

{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Project status</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <form action="" method="post">{% csrf_token %}
                                    <p>Are you sure you want to delete "{{ object }}"?</p>
                                    <input type="submit" value="Confirm" />
                                </form>
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}

templates/admission/admission_detail.html
{% extends 'master.html' %}

{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Project status</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                               {{admisssion_details.admission_date}}
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}

templates/admission/admission_nav.html
<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-chart-pie" style=""></i>
    </div>
    <a href="{% url 'fee:fee_main'%}">All (homex)</a> 
</div>

<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-chart-bar" style=""></i>
    </div>
    <a href="{% url 'fee:generate_challan'%}">Generate Challan</a> 
</div>

<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-credit-card" style=""></i>
    </div>
    <a href="{% url 'fee:unpaid_challan'%}">Pay Challan</a> 
</div>

    <div class="mycard">
        <div class="myicon">
            <i class="typcn typcn-chart-pie-outline" style=""></i>
        </div>
        <a href="{% url 'fee:fee_defaulter'%}">Fee Defaulters</a> 
    </div>
    
<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-user" style=""></i>
    </div>
    <a href="{% url 'fee:salary'%}">Employee Salary</a> 
</div>

<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-chart-line" style=""></i>
    </div>
    <a href="{% url 'account:expense_view'%}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Expense&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a> 
</div>

<div class="mycard">
    <div class="myicon">
        <i class="typcn typcn-chart-area-outline" style=""></i>
    </div>
    <a href="{% url 'account:income_view'%}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a> 
</div>

templates/admission/admission_view.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block body %}
                    <div class="body-content">
                        <div class="card mb-4">
                            <div class="card-header">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <h6 class="fs-17 font-weight-600 mb-0">Project status</h6>
                                    </div>
                                    <div class="text-right">
                                        <div class="actions">
                                            <a href="#" class="action-item"><i class="ti-reload"></i></a>
                                            <div class="dropdown action-item" data-toggle="dropdown">
                                                <a href="#" class="action-item"><i class="ti-more-alt"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a href="#" class="dropdown-item">Refresh</a>
                                                    <a href="#" class="dropdown-item">Manage Widgets</a>
                                                    <a href="#" class="dropdown-item">Settings</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                               <a href="{% url 'student:admission_create' %}" class="btn btn-primary">New Admission</a>
                                <div class="table-responsive my-4">
                                  <table id="example" class="table display table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th>S-No</th>
                                              <th>Photo</th>
                                              <th>Class</th>
                                              <th>Section</th>
                                              <th>Registration</th>
                                              <th>Name</th>
                                              <th>Father Name</th>
                                              <th>Contact</th>
                                              <th>Tution Fee</th>
                                              <th>Action</th>

                                          </tr>
                                      </thead>
                                      <tbody>
                                       
                                       {% for admission in admission_view %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td><img src="{{ admission.photo.url }}" alt="" style="width:40px;"></td>
                                                <td>{{ admission.admission_class }}</td>
                                                <td>{{ admission.admission_section }}</td>
                                                <td>{{ admission.admission_registration }}</td>
                                                <td>{{ admission.name_of_student }}</td>
                                                <td>{{ admission.father_name }}</td>
                                                <td>{{ admission.contact }}</td>
                                                <td>{{ admission.monthly_tution_fee }}</td>
                                                <td>
                                                <a href="{% url 'student:admission_update' pk=admission.pk %}"> Update </a> | 
                                                <a href="{% url 'student:admission_delete' pk=admission.pk %}"> Delete </a> | 
                                                <a href="{% url 'student:view_individual_marks' student_name=admission.name_of_student %}"> View </a>
                                                </td>
                                            </tr>
                                       {% endfor %}

                                      </tbody>

                                  </table>
                              </div> 
                            </div>
                        </div>
                    </div><!--/.body content-->
{% endblock %}